export { HomePage } from './pages/HomePage'
export { HomePage as FoodscapingHome } from './pages/HomePage'
export { HomePage as CoopersFoodscapingHome } from './pages/HomePage'
export { FoodscapingLayout } from './layout/FoodscapingLayout'
export { AboutPage } from './pages/AboutPage'
export { ServicesPage } from './pages/ServicesPage'
export { GalleryPage } from './pages/GalleryPage'
export { ContactPage } from './pages/ContactPage'
export { ServiceAreaPage } from './pages/ServiceAreaPage'
